version: "3"
services:
  db:
    container_name: stepann0-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: balances
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
  web:
    container_name: stepann0-api-service
    build: .
    volumes:
      - .:/app/
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  db-data:
    driver: local

networks:
  fullstack:
    driver: bridge